/* AUTO-GENERATED FILE. DO NOT MODIFY !!!
*
* This config file is automatically generated by build system.
* It should not be modified by hand.
*/

#ifndef OPENSDK_CONFIG_H
#define OPENSDK_CONFIG_H

#ifdef __cplusplus
extern "C" {
#endif


//
// config of linux-ubuntu-6.2.0_64Bit
//

//
// board
//
#define OPERATING_SYSTEM 100
#define ENABLE_WIRED 1
#define LITTLE_END 1
#define WLAN_DEV "wlan0"
#define WLAN_AP "wlan1"
// CONFIG_NL80211 is not set
#define WIFI_DB_PATH "./tuya_db_files"
// end of board

// CONFIG_ENABLE_LIBLWIP is not set

//
// mbedtls Config
//
// CONFIG_ENABLE_BLACK_WHITE_LIST is not set
// #define MBEDTLS_CONFIG_FILE "tuya_tls_config.h"
#define MAX_SECURITY_LEVEL 1
#define TUYA_SECURITY_LEVEL 1
// CONFIG_ENABLE_MBEDTLS_DEBUG is not set
// CONFIG_ENABLE_CUSTOM_CONFIG is not set
// end of mbedtls Config

//
// System function Config
//
#define ENABLE_LOG 1
#define STACK_SIZE_TIMERQ 4096
#define STACK_SIZE_WORK_QUEUE 5120
#define MAX_NODE_NUM_WORK_QUEUE 100
#define STACK_SIZE_MSG_QUEUE 4096
#define MAX_NODE_NUM_MSG_QUEUE 100
// end of System function Config

//
// tuya cloud
//
// CONFIG_ENABLE_BT_SERVICE=y
// CONFIG_ENABLE_BT_NETCFG=y
// CONFIG_ENABLE_BT_CTRL=y
// CONFIG_BT_ADV_INTERVAL_MIN=30
// CONFIG_BT_ADV_INTERVAL_MAX=60
// CONFIG_BT_REMOTE_CTRL_SCAN_INTERVAL=30
// CONFIG_BT_REMOTE_CTRL_SCAN_WINDOWS=10
// CONFIG_TUYA_BLE_VER=4
// CONFIG_ENABLE_TAL_BLUETOOTH=y
// CONFIG_TAL_BLE_SERVICE_VERSION=2
// CONFIG_ENABLE_NIMBLE is not set
// end of tuya cloud


#ifdef __cplusplus
}
#endif

#endif  // OPENSDK_CONFIG_H


